---
apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: registry-creds
    namespace: kube-system
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/minikube-addons: registry-creds
      version: v1.9
  spec:
    replicas: 1
    selector:
      addonmanager.kubernetes.io/mode: Reconcile
      name: registry-creds
      version: v1.9
    template:
      metadata:
        labels:
          addonmanager.kubernetes.io/mode: Reconcile
          name: registry-creds
          version: v1.9
      spec:
        containers:
          name: registry-creds
          image: registry.hub.docker.com/upmcenterprises/registry-creds:1.9
          imagePullPolicy: Always
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY_ID
                name: registry-creds-ecr
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_ACCESS_KEY
                name: registry-creds-ecr
          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                key: AWS_SESSION_TOKEN
                name: registry-creds-ecr
          - name: awsregion
            valueFrom:
              secretKeyRef:
                key: aws-region
                name: registry-creds-ecr
          - name: awsaccount
            valueFrom:
              secretKeyRef:
                key: aws-account
                name: registry-creds-ecr
          - name: aws_assume_role
            valueFrom:
              secretKeyRef:
                key: aws-assume-role
                name: registry-creds-ecr
          - name: awsregion
            valueFrom:
              secretKeyRef:
                key: aws-region
                name: registry-creds-ecr
          - name: DOCKER_PRIVATE_REGISTRY_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DOCKER_PRIVATE_REGISTRY_PASSWORD
                name: registry-creds-dpr
          - name: DOCKER_PRIVATE_REGISTRY_SERVER
            valueFrom:
              secretKeyRef:
                key: DOCKER_PRIVATE_REGISTRY_SERVER
                name: registry-creds-dpr
          - name: DOCKER_PRIVATE_REGISTRY_USER
            valueFrom:
              secretKeyRef:
                key: DOCKER_PRIVATE_REGISTRY_USER
                name: registry-creds-dpr
          - name: gcrurl
            valueFrom:
              secretKeyRef:
                key: gcrurl
                name: registry-creds-gcr
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /root/.config/gcloud
            name: gcr-creds
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: gcr-creds
          secret:
            defaultMode: 420
            items:
            - key: application_default_credentials.json
              path: application_default_credentials.json
            secretName: registry-creds-gcr
